version: 2.1
executors:
  builder:
    docker:
      - image: circleci/golang:1.14.4
  docker-publisher:
    environment:
      IMAGE_NAME: playmean/scoper
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  artifacts:
    executor: builder
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Build executable
          command: make
      - store_artifacts:
          path: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/dist/scoper
          destination: scoper
  docker:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run:
          name: Build AMD64 Docker image
          command: docker build --build-arg ARCH=amd64 --tag $IMAGE_NAME:latest .
      - run:
          name: Build ARM Docker image
          command: docker build --build-arg ARCH=arm --tag $IMAGE_NAME:arm .
      - run:
          name: Build ARM64 Docker image
          command: docker build --build-arg ARCH=arm64 --tag $IMAGE_NAME:arm64 .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo "{\"experimental\": \"enabled\"}" > /etc/docker/daemon.json'
            sudo systemctl restart docker
          EOF
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
      - run:
          name: Create docker manifest
          command: docker manifest create $IMAGE_NAME:latest $IMAGE_NAME:arm $IMAGE_NAME:arm64
      - run:
          name: Publish manifest to Docker Hub
          command: docker manifest push --purge $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - artifacts:
          filters:
            branches:
              only: master
      - docker:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - docker
          filters:
            branches:
              only: master
